# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.dirsLabel = QtWidgets.QLabel(self.centralwidget)
        self.dirsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dirsLabel.setObjectName("dirsLabel")
        self.top_layout.addWidget(self.dirsLabel)
        self.selectedDirsLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectedDirsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedDirsLabel.setObjectName("selectedDirsLabel")
        self.top_layout.addWidget(self.selectedDirsLabel)
        self.verticalLayout.addLayout(self.top_layout)
        self.mid_layout = QtWidgets.QHBoxLayout()
        self.mid_layout.setObjectName("mid_layout")
        self.dirsSelection = QtWidgets.QListWidget(self.centralwidget)
        self.dirsSelection.setObjectName("dirsSelection")
        self.mid_layout.addWidget(self.dirsSelection)
        self.dirsSelected = QtWidgets.QListWidget(self.centralwidget)
        self.dirsSelected.setObjectName("dirsSelected")
        self.mid_layout.addWidget(self.dirsSelected)
        self.verticalLayout.addLayout(self.mid_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem)
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setStyleSheet("background-color: rgba(170, 0, 0, 150)")
        self.cancelBtn.setObjectName("cancelBtn")
        self.bottom_layout.addWidget(self.cancelBtn)
        self.backupBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backupBtn.setStyleSheet("background-color: rgba(0, 85, 0,150);")
        self.backupBtn.setObjectName("backupBtn")
        self.bottom_layout.addWidget(self.backupBtn)
        self.verticalLayout.addLayout(self.bottom_layout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 32))
        self.menubar.setObjectName("menubar")
        self.menuADB_setu = QtWidgets.QMenu(self.menubar)
        self.menuADB_setu.setObjectName("menuADB_setu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionread_ADB_devices = QtWidgets.QAction(MainWindow)
        self.actionread_ADB_devices.setObjectName("actionread_ADB_devices")
        self.menuADB_setu.addAction(self.actionread_ADB_devices)
        self.menubar.addAction(self.menuADB_setu.menuAction())

        self.retranslateUi(MainWindow)
        self.cancelBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADB BACKUP TOOL"))
        self.dirsLabel.setText(_translate("MainWindow", "Dirs selection"))
        self.selectedDirsLabel.setText(_translate("MainWindow", "Selected dirs"))
        self.cancelBtn.setText(_translate("MainWindow", "Cancel"))
        self.backupBtn.setText(_translate("MainWindow", "Backup"))
        self.menuADB_setu.setTitle(_translate("MainWindow", "ADB setup"))
        self.actionread_ADB_devices.setText(_translate("MainWindow", "read ADB devices"))
        self.actionread_ADB_devices.setStatusTip(_translate("MainWindow", "refresh ADB devices"))
        self.actionread_ADB_devices.setShortcut(_translate("MainWindow", "F5"))
